# Generated by Django 5.0.3 on 2024-03-24 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and contain at least one uppercase letter and one digit.', regex='^(?=.*[A-Z])(?=.*\\d).{8,}$')]),
        ),
    ]
